added links to rules
swccgpc/swccg-card-json pull request #152
Opened 2022-01-16 01:32 UTC by DevoKun

2022-01-16 01:43 UTC, thomasmarlin reviewed
I like the idea of this change!  Having direct links to confusing stuff makes a lot of sense. This is especially awesome for things like the special Tatooine / Bespin / etc setup. That's very useful.

My concern however is with putting the "Generic Systems Deployment" on every single system. Likewise, having the creature rules on every creature.   I can see some the benefits of having it inside the DB. However, I also get a little worried about bloat in the DB too. For example, we wouldn't put "Battle Rules" on every card that battles, we wouldn't put "Deployment Rules" on every card that deploys.  I'm not sure where to draw the line on that one.

This may make a good discussion in Slack

2022-01-16 01:47 UTC, thomasmarlin requested changes

2022-01-16 01:47 UTC, thomasmarlin commented on Dark.json
> +      "rules": [{"name":"Bluff Rules", "url":"https://www.starwarsccg.org/bluff-rules/"}],
Should be merged into 1 array

2022-01-17 03:22 UTC, thomasmarlin commented on Dark.json
> +      "rules": [{"name":"Creature Rules", "url":"https://www.starwarsccg.org/creature-rules/"}],
Greg noticed this on Slack. We need to remove these "Creature Rules" entries for Creature Vehicles (Only including them for actual creatures).

2022-01-17 03:25 UTC, thomasmarlin commented on Light.json
> +      "rules": [{"name":"Generic Systems Deployment", "url":"https://www.starwarsccg.org/location-deployment-specifics-general"}],
Looks like the "Generic" rules were removed for the Dark cards, but are still present for the light-side.  I'm guessing you are still working on this (this is mostly a note for whoever reviews this later to make sure to check both files)

2022-01-17 15:49 UTC, scottrick commented
These rule links are really great and I think could be very handy moving forward.  I have two concerns:
* Is there a process to make sure that as the official rules PDF is updated, these rules pages are also updated?  I worry about them getting out of sync.
* It might be worth aligning the URL format before everything starts using it:
Instead of https://www.starwarsccg.org/creature-rules/, maybe we should have the rules all be something like:  https://www.starwarsccg.org/rules/creatures/.  https://www.starwarsccg.org/rules/ could contain a directory of all available special rules, or an online version of the pdf, or something else.

2022-01-17 16:34 UTC, DevoKun commented
> These rule links are really great and I think could be very handy moving forward. I have two concerns:
> 
> * Is there a process to make sure that as the official rules PDF is updated, these rules pages are also updated?  I worry about them getting out of sync.
> * It might be worth aligning the URL format before everything starts using it:
>   Instead of https://www.starwarsccg.org/creature-rules/, maybe we should have the rules all be something like:  https://www.starwarsccg.org/rules/creatures/

These rules URL's are not new website content. They have been on the site for years. The only change here is a quicklink to them.

2022-01-19 03:49 UTC, thomasmarlin commented
@DevoKun  - drop a note here once this is ready for re-review again (and conflicts resolved). I think a bunch of these will be great to get in

2022-01-23 14:50 UTC, closed without merging